Fantastyka2/Controllers/AboutFantasyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fantastyka.Controllers
{
    public class AboutFantasyController : Controller
    {
        public ActionResult AboutFantasy()
        {
            return View();
        }
    }
}

Fantastyka2/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fantastyka.Controllers
{
    public class AuthorsController : Controller
    {
        public ActionResult Authors()
        {
            return View();
        }
    }
}

Fantastyka2/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fantastyka2.Models;
using Fantastyka2.Repositories;
using Microsoft.AspNet.Identity;

namespace Fantastyka2.Controllers
{
    public class BooksController : Controller
    {
        // GET: Books
        public ActionResult Books()
        {
            var booksViewMoel = new BooksViewModel();
            var repo = new FantasyRepository();
            booksViewMoel.Books = repo.GetAllBooks();
            return View(booksViewMoel);
        }

        [HttpPost]
        public ActionResult Books(BooksViewModel model)
        {

            var request = Request.Form["SelectedSources"];
            if (request != null)
            {
                var checkedIds = request.Split(',').ToList();
                var repo = new FantasyRepository();
                repo.AddToCart(checkedIds, User.Identity.GetUserId());
            }
            
            return Books();
        }

        [HttpPost]
        public JsonResult GetBooksForCategory(string category)
        {
            try
            {
                //in real application made a better load / retrieving
                var emp = new List<Book>();
                var repo = new FantasyRepository();
                emp = repo.GetAllBooks();

                if(category != "Nie wybrano")
                    emp.RemoveAll(item => item.Category != category);

                return Json(new { ok = true, data = emp, message = "ok" });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, message = ex.Message });
            }
        }
    }
}

Fantastyka2/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fantastyka.Models;

namespace Fantastyka.Controllers
{
    public class SurveyController : Controller
    {
        public ActionResult Survey()
        {
            var newModel = new SurveyModel()
            {
                Hidden = true
            };
            return View(newModel);
        }

        [HttpPost]
        public ActionResult Survey(SurveyModel model)
        {
            if (Request.HttpMethod == "POST" && ModelState.IsValid)
            {
                ModelState.Clear();
                var text = model.Name + " " + model.Email + " " + model.Author + " " + model.Title + " " + model.Readed + " " + model.TimesReaded + " " + model.Rating + " " + model.Publisher;
                var newMOdel = new SurveyModel()
                {
                    Hidden = false,
                    Result = text
                };
                return View(newMOdel);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Clear(SurveyModel model)
        {
            return Survey();
        }
    }
}

Fantastyka2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/pageSchema.css")
    @Scripts.Render("~/bundles/modernizr")
    @*@Scripts.Render("~/bundles/jquery.datetimepicker")*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Literatura Fantasy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Index", "Index", "Home")</li>
                    <li>@Html.ActionLink("O fantastyce", "AboutFantasy", "AboutFantasy")</li>
                    <li>@Html.ActionLink("Polscy Pisarze", "Authors", "Authors")</li>
                    <li>@Html.ActionLink("Ankieta", "Survey", "Survey")</li>
                    <li>@Html.ActionLink("Ksiazki", "Books", "Books")</li>
                    @{
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Dodaj książkę", "AddBook", "AddBook")</li>
                        }
                        if (User.IsInRole("User"))
                        {
                            <li>@Html.ActionLink("Koszyk", "Index", "ShoppingCart")</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>
    <footer id="footer">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        <p>&copy;Agata Kondraczyk || Artur Markowski</p>
    </footer>
  
</body>
</html>